[package]
name = "raytracer"
version = "0.1.0"
authors = ["Nishant Mahajan <nishant.mahajanXVII@gmail.com>"]
edition = "2018"

[dependencies]
impl_ops = "0.1.1"
png = "0.16.8"
rand = "0.7.3"
rayon = "1.5.0"
